#!/bin/bash
 
git add -A
git commit -m "Resolve test"
git merge step4-test4

printf '\033[0;32m'
echo ""
echo ""
echo "========================"
echo "===  STEP 4 - Test 4 ==="
echo "========================"
echo ""
echo ""
printf '\033[0m'
